### ISSUE TITLE
Can no longer rebuild cache

### ISSUE THREAD

**Issue by stef204** [MarkHedleyJones/dmenu-extended#157]
`dmenu-extended-git r421.7ad25c0-1`

This problem has started to appear: I can no longer rebuild the cache so `dmenu-extended` no longer shows new apps I might install.

How do I start trouble shooting?

**Comment by stef204** [comment]
I just found out what the culprit was:


```
% dmenu_extended_cache_build
Traceback (most recent call last):
  File "/usr/bin/dmenu_extended_cache_build", line 8, in <module>
    sys.exit(build_cache())
  File "/usr/lib/python3.10/site-packages/dmenu_extended/main.py", line 2266, in build_cache
    d.build_cache()
  File "/usr/lib/python3.10/site-packages/dmenu_extended/main.py", line 1052, in build_cache
    applications = self.scan_applications()
  File "/usr/lib/python3.10/site-packages/dmenu_extended/main.py", line 898, in scan_applications
    with open(pathname, "r", errors="ignore") as f:
PermissionError: [Errno 13] Permission denied: '/usr/share/applications/someapp.desktop'
```
` '/usr/share/applications/someapp.desktop'` had `600` permission.  Changing that to `655` resolved the issue.
Not sure this is worth taking a look at or not.  Probably not.....

I'll close it.

**Comment by stef204** [comment]
Let me close this.

**Comment by MarkHedleyJones** [comment]
Glad you found a solution :smile:
