### ISSUE TITLE
Folders with colon character

### ISSUE THREAD

**Issue by uaristocles** [MarkHedleyJones/dmenu-extended#61]
Folders containing the colon character (':') are not properly opened. Running it from a terminal throws an error message:
```
/home/user/Documents/Area: subject/
/home/user/Documents/Area: subject/
Traceback (most recent call last):
  File "dmenu_extended_run", line 7, in <module>
    dmenu_extended.run(*sys.argv)
  File "/home/user/bin/dmenu_extended.py", line 1850, in run
    d.execute(command)
  File "/home/user/bin/dmenu_extended.py", line 664, in execute
    return subprocess.call(command)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Thank you for your work!

**Comment by MarkHedleyJones** [comment]
Hi there,
Thanks for reporting your findings.
I just pushed a change that should solve the issue you're having.
Let me know how you get on.

**Comment by uaristocles** [comment]
Great, now it works perfectly fine. Thank you for the fix!
