### ISSUE TITLE
File path with spaces does not work

### ISSUE THREAD

**Issue by anubhabckbty** [MarkHedleyJones/dmenu-extended#88]
I am using Arch+rofi+dmenu_extended.

dmenu_extended_run is working as expected for file paths with no spaces in them. 

For file paths with spaces in them, the search is working well, but when I press [enter] to open the file, dmenu_extended_run quits throwing the following error:
```
Traceback (most recent call last):
  File "/sbin/dmenu_extended_run", line 7, in <module>
    dmenu_extended.run(*sys.argv)
  File "/usr/lib/python3.7/site-packages/dmenu_extended.py", line 1976, in run
    handle_command(d, out)
  File "/usr/lib/python3.7/site-packages/dmenu_extended.py", line 1559, in handle_command
    if parts[0] in d.scan_binaries():
  File "/usr/lib/python3.7/site-packages/dmenu_extended.py", line 804, in scan_binaries
    for binary in os.listdir(path):
NotADirectoryError: [Errno 20] Not a directory: '/usr/bin/env'
```

**Comment by MarkHedleyJones** [comment]
Hi there,
Sorry is has taken so long to get to this.
I believe the issue has been fixed.
Please install the latest version and let me know if the issue has been resolved.
Thanks.

**Comment by anubhabckbty** [comment]
Yep, the issue has been resolved. Thanks!
